const DEFAULT_HANJA = [
  { hanja: "家", reading: "가", meaning: "집 가" },
  { hanja: "角", reading: "각", meaning: "뿔 각" },
  { hanja: "干", reading: "간", meaning: "방패 간" },
  { hanja: "甘", reading: "감", meaning: "달 감" },
  { hanja: "車", reading: "거", meaning: "수레 거" },
  { hanja: "犬", reading: "견", meaning: "개 견" },
  { hanja: "見", reading: "견", meaning: "볼 견" },
  { hanja: "高", reading: "고", meaning: "높을 고" },
  { hanja: "鼓", reading: "고", meaning: "북 고" },
  { hanja: "谷", reading: "곡", meaning: "골짜기 곡" },
  { hanja: "骨", reading: "골", meaning: "뼈 골" }, 
  { hanja: "工", reading: "공", meaning: "장인 공" },
  { hanja: "口", reading: "구", meaning: "입 구" },
  { hanja: "龜", reading: "구", meaning: "거북 구" },
  { hanja: "弓", reading: "궁", meaning: "활 궁" },
  { hanja: "鬼", reading: "귀", meaning: "귀신 귀" },
  { hanja: "斤", reading: "근", meaning: "도끼 근" },
  { hanja: "金", reading: "금", meaning: "쇠 금" },
  { hanja: "己", reading: "기", meaning: "몸 기" },
  { hanja: "女", reading: "녀", meaning: "여자 녀" },
  { hanja: "大", reading: "대", meaning: "클 대" },
  { hanja: "刀", reading: "도", meaning: "칼 도" },
  { hanja: "斗", reading: "두", meaning: "말 두" },
  { hanja: "豆", reading: "두", meaning: "콩 두" },
  { hanja: "力", reading: "력", meaning: "힘 력" },
  { hanja: "老", reading: "로", meaning: "늙을 로" },
  { hanja: "鹿", reading: "록", meaning: "사슴 록" },
  { hanja: "龍", reading: "룡", meaning: "용 룡" },
  { hanja: "里", reading: "리", meaning: "마을 리" },
  { hanja: "立", reading: "립", meaning: "설 립" },
  { hanja: "馬", reading: "마", meaning: "말 마" },
  { hanja: "面", reading: "면", meaning: "얼굴 면" },
  { hanja: "毛", reading: "모", meaning: "털 모" },
  { hanja: "木", reading: "목", meaning: "나무 목" },
  { hanja: "目", reading: "목", meaning: "눈 목" },
  { hanja: "文", reading: "문", meaning: "글월 문" },
  { hanja: "門", reading: "문", meaning: "문 문" },
  { hanja: "米", reading: "미", meaning: "쌀 미" },
  { hanja: "方", reading: "방", meaning: "모 방" },
  { hanja: "白", reading: "백", meaning: "흴 백" },
  { hanja: "卜", reading: "복", meaning: "점 복" },
  { hanja: "父", reading: "부", meaning: "아버지 부" },
  { hanja: "比", reading: "비", meaning: "견줄 비" },
  { hanja: "非", reading: "비", meaning: "아닐 비" },
  { hanja: "飛", reading: "비", meaning: "날 비" },
  { hanja: "鼻", reading: "비", meaning: "코 비" },
  { hanja: "士", reading: "사", meaning: "선비 사" },
  { hanja: "山", reading: "산", meaning: "산 산" },
  { hanja: "色", reading: "색", meaning: "빛 색" },
  { hanja: "生", reading: "생", meaning: "날 생" },
  { hanja: "夕", reading: "석", meaning: "저녁 석" },
  { hanja: "石", reading: "석", meaning: "돌 석" },
  { hanja: "舌", reading: "설", meaning: "혀 설" },
  { hanja: "小", reading: "소", meaning: "작을 소" },
  { hanja: "手", reading: "수", meaning: "손 수" },
  { hanja: "水", reading: "수", meaning: "물 수" },
  { hanja: "首", reading: "수", meaning: "머리 수" },
  { hanja: "示", reading: "시", meaning: "보일 시" },
  { hanja: "矢", reading: "시", meaning: "화살 시" },
  { hanja: "食", reading: "식", meaning: "먹을 식" },
  { hanja: "臣", reading: "신", meaning: "신하 신" },
  { hanja: "身", reading: "신", meaning: "몸 신" },
  { hanja: "辛", reading: "신", meaning: "매울 신" },
  { hanja: "心", reading: "심", meaning: "마음 심" },
  { hanja: "十", reading: "십", meaning: "열 십" },
  { hanja: "氏", reading: "씨", meaning: "성씨 씨" },
  { hanja: "牙", reading: "아", meaning: "어금니 아" },
  { hanja: "羊", reading: "양", meaning: "양 양" },
  { hanja: "魚", reading: "어", meaning: "물고기 어" },
  { hanja: "言", reading: "언", meaning: "말씀 언" },
  { hanja: "玉", reading: "옥", meaning: "구슬 옥" },
  { hanja: "瓦", reading: "와", meaning: "기와 와" },
  { hanja: "曰", reading: "왈", meaning: "가로 왈" },
  { hanja: "用", reading: "용", meaning: "쓸 용" },
  { hanja: "又", reading: "우", meaning: "또 우" },
  { hanja: "牛", reading: "우", meaning: "소 우" },
  { hanja: "雨", reading: "우", meaning: "비 우" },
  { hanja: "羽", reading: "우", meaning: "깃 우" },
  { hanja: "月", reading: "월", meaning: "달 월" },
  { hanja: "肉", reading: "육", meaning: "고기 육" },
  { hanja: "乙", reading: "을", meaning: "새 을" },
  { hanja: "音", reading: "음", meaning: "소리 음" },
  { hanja: "衣", reading: "의", meaning: "옷 의" },
  { hanja: "二", reading: "이", meaning: "두 이" },
  { hanja: "而", reading: "이", meaning: "말이을 이" },
  { hanja: "耳", reading: "이", meaning: "귀 이" },
  { hanja: "人", reading: "인", meaning: "사람 인" },
  { hanja: "一", reading: "일", meaning: "하나 일" },
  { hanja: "日", reading: "일", meaning: "해 일" },
  { hanja: "入", reading: "입", meaning: "들 입" },
  { hanja: "子", reading: "자", meaning: "아들 자" },
  { hanja: "自", reading: "자", meaning: "스스로 자" },
  { hanja: "長", reading: "장", meaning: "길 장" },
  { hanja: "赤", reading: "적", meaning: "붉을 적" },
  { hanja: "田", reading: "전", meaning: "밭 전" },
  { hanja: "齊", reading: "제", meaning: "가지런할 제" },
  { hanja: "鳥", reading: "조", meaning: "새 조" },
  { hanja: "足", reading: "족", meaning: "발 족" },
  { hanja: "走", reading: "주", meaning: "달릴 주" },
  { hanja: "舟", reading: "주", meaning: "배 주" },
  { hanja: "竹", reading: "죽", meaning: "대나무 죽" },
  { hanja: "支", reading: "지", meaning: "지탱할 지" },
  { hanja: "止", reading: "지", meaning: "그칠 지" },
  { hanja: "至", reading: "지", meaning: "이를 지" },
  { hanja: "辰", reading: "진", meaning: "별 진" },
  { hanja: "川", reading: "천", meaning: "내 천" },
  { hanja: "靑", reading: "청", meaning: "푸를 청" },
  { hanja: "寸", reading: "촌", meaning: "마디 촌" },
  { hanja: "齒", reading: "치", meaning: "이 치" },
  { hanja: "土", reading: "토", meaning: "흙 토" },
  { hanja: "八", reading: "팔", meaning: "여덟 팔" },
  { hanja: "貝", reading: "패", meaning: "조개 패" },
  { hanja: "風", reading: "풍", meaning: "바람 풍" },
  { hanja: "皮", reading: "피", meaning: "가죽 피" },
  { hanja: "行", reading: "행", meaning: "다닐 행" },
  { hanja: "香", reading: "향", meaning: "향기 향" },
  { hanja: "革", reading: "혁", meaning: "가죽 혁" },
  { hanja: "玄", reading: "현", meaning: "검을 현" },
  { hanja: "血", reading: "혈", meaning: "피 혈" },
  { hanja: "穴", reading: "혈", meaning: "구멍 혈" },
  { hanja: "火", reading: "화", meaning: "불 화" },
  { hanja: "禾", reading: "화", meaning: "벼 화" },
  { hanja: "黃", reading: "황", meaning: "누를 황" },
  { hanja: "黑", reading: "흑", meaning: "검을 흑" }
  ];

const DEFAULT_SAJA = [
  { idiom: "知音", reading: "지음", meaning: "백아(伯牙)와 종자기(鍾子期) 사이의 고사로부터 (거문고) 소리를 알아 듣는다는 뜻에서 유래." },
  { idiom: "水魚之交", reading: "수어지교", meaning: "고기와 물과의 관계처럼 떨어질 수 없는 특별한 친분" },
  { idiom: "莫逆之友", reading: "막역지우", meaning: "서로 거역하지 아니하는 친구" },
  { idiom: "金蘭之契", reading: "금란지계", meaning: "금이나 난초와 같이 귀하고 향기로움을 풍기는 친구의 사이의 맺음(사귐)" },
  { idiom: "管鮑之交", reading: "관포지교", meaning: "관중과 포숙의 사귐과 같은 친구 사이의 허물없는 교재" },
  { idiom: "竹馬故友", reading: "죽마고우", meaning: "어릴 때, 대나무말을 타고 놀며 같이 자란 친구" },
  { idiom: "刎頸之交", reading: "문경지교", meaning: "대신 목을 내주어도 좋을 정도로 친한 친구의 사귐" },
  { idiom: "桑田碧海", reading: "상전벽해", meaning: "뽕나무밭이 푸른 바다가 됨" },
  { idiom: "天旋地轉", reading: "천선지전", meaning: "세상일이 크게 변함" },
  { idiom: "吳越同舟", reading: "오월동주", meaning: "서로 원수의 사이인 오나라 사람과 월나라 사람이 같은 배를 탐" },
  { idiom: "漁父之利", reading: "어부지리", meaning: "조개와 도요새가 서로 버티는 통에 어부가 둘을 다 잡아 이득을 봄" },
  { idiom: "犬兎之爭", reading: "견토지쟁", meaning: "개와 토끼가 싸우다 지쳐서 둘다 쓰러져 숨져 있는 것을 지나가던 농부가 주워서 이득을 봄" },
  { idiom: "白眉", reading: "백미", meaning: "마씨 오형제 중에서 가장 재주가 뛰어난 맏이 마량이 눈썹이 희었다는 데서 나온 말" },
  { idiom: "鐵中錚錚", reading: "철중쟁쟁", meaning: "같은 동아리 가운데 가장 뛰어난 사람을 비유" },
  { idiom: "高麗公事三日", reading: "고려공사삼일", meaning: "고려의 정책이나 법령은 기껏해야 사흘밖에 가지 못함" },
  { idiom: "早變夕改", reading: "조변석개", meaning: "아침 저녁으로 뜯어 고침" },
  { idiom: "朝令暮改", reading: "조령모개", meaning: "아침에 영(명령)을 내리고 저녁에 다시 고침" }
];
