const DEFAULT_HANJA = [
  { hanja: "學", reading: "학", meaning: "배울 학" },
  { hanja: "問", reading: "문", meaning: "물을 문" },
  { hanja: "知", reading: "지", meaning: "알 지" },
  { hanja: "識", reading: "식", meaning: "알 식" },
  { hanja: "孝", reading: "효", meaning: "효도 효" },
  { hanja: "仁", reading: "인", meaning: "어질 인" },
  { hanja: "禮", reading: "예", meaning: "예절 예" },
  { hanja: "信", reading: "신", meaning: "믿음 신" },
  { hanja: "勤", reading: "근", meaning: "부지런 근" },
  { hanja: "廉", reading: "염", meaning: "마를 염" },
  { hanja: "正", reading: "정", meaning: "바를 정" },
  { hanja: "義", reading: "의", meaning: "옳을 의" },
  { hanja: "自", reading: "자", meaning: "스스로 자" },
  { hanja: "律", reading: "율", meaning: "법 율" },
  { hanja: "感", reading: "감", meaning: "느낄 감" },
  { hanja: "謝", reading: "사", meaning: "사례할 사" },
  { hanja: "忍", reading: "인", meaning: "참을 인" },
  { hanja: "勇", reading: "용", meaning: "용기 용" },
  { hanja: "夢", reading: "몽", meaning: "꿈 몽" },
  { hanja: "和", reading: "화", meaning: "화할 화" }
];

const DEFAULT_SAJA = [
  { idiom: "知音", reading: "지음", meaning: "백아(伯牙)와 종자기(鍾子期) 사이의 고사로부터 (거문고) 소리를 알아 듣는다는 뜻에서 유래." },
  { idiom: "水魚之交", reading: "수어지교", meaning: "고기와 물과의 관계처럼 떨어질 수 없는 특별한 친분" },
  { idiom: "莫逆之友", reading: "막역지우", meaning: "서로 거역하지 아니하는 친구" },
  { idiom: "金蘭之契", reading: "금란지계", meaning: "금이나 난초와 같이 귀하고 향기로움을 풍기는 친구의 사이의 맺음(사귐)" },
  { idiom: "管鮑之交", reading: "관포지교", meaning: "관중과 포숙의 사귐과 같은 친구 사이의 허물없는 교재" },
  { idiom: "竹馬故友", reading: "죽마고우", meaning: "어릴 때, 대나무말을 타고 놀며 같이 자란 친구" },
  { idiom: "刎頸之交", reading: "문경지교", meaning: "대신 목을 내주어도 좋을 정도로 친한 친구의 사귐" },
  { idiom: "桑田碧海", reading: "상전벽해", meaning: "뽕나무밭이 푸른 바다가 됨" },
  { idiom: "天旋地轉", reading: "천선지전", meaning: "세상일이 크게 변함" },
  { idiom: "吳越同舟", reading: "오월동주", meaning: "서로 원수의 사이인 오나라 사람과 월나라 사람이 같은 배를 탐" },
  { idiom: "漁父之利", reading: "어부지리", meaning: "조개와 도요새가 서로 버티는 통에 어부가 둘을 다 잡아 이득을 봄" },
  { idiom: "犬兎之爭", reading: "견토지쟁", meaning: "개와 토끼가 싸우다 지쳐서 둘다 쓰러져 숨져 있는 것을 지나가던 농부가 주워서 이득을 봄" },
  { idiom: "白眉", reading: "백미", meaning: "마씨 오형제 중에서 가장 재주가 뛰어난 맏이 마량이 눈썹이 희었다는 데서 나온 말" },
  { idiom: "鐵中錚錚", reading: "철중쟁쟁", meaning: "같은 동아리 가운데 가장 뛰어난 사람을 비유" },
  { idiom: "高麗公事三日", reading: "고려공사삼일", meaning: "고려의 정책이나 법령은 기껏해야 사흘밖에 가지 못함" },
  { idiom: "早變夕改", reading: "조변석개", meaning: "아침 저녁으로 뜯어 고침" },
  { idiom: "朝令暮改", reading: "조령모개", meaning: "아침에 영(명령)을 내리고 저녁에 다시 고침" }
];
